{% set name = "gempy-engine" %}
{% set version = "2025.1.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gempy_engine-{{ version }}.tar.gz
  sha256: c22d13380c2621ac79a9155d11d87f3e419326c67105825f5838f066c2aacdfc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - numpy
    - python-dotenv >=1.0.1,<1.1.dev0

test:
  imports:
    - gempy_engine
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/gempy-project/gempy_engine
  summary: A Python package necessary for GemPy.
  description: A Python package necessary for GemPy.
  license: EUPL-1.2
  license_file: LICENSE
  dev_url: https://github.com/gempy-project/gempy_engine

extra:
  recipe-maintainers:
    - conda-forge/gempy
